function defaultHotkeyHelpFcn(key_in)
% DEFAULTHOTKEYHELPFCN  Default function mapping hotkeys for video scoring
%
%  Issued whenever 'h' is pressed for nigeLab.Block.scoreVideo; describes
%  what the different hotkeys do. A new version should be made to match any
%  ad hoc HotkeyFcn placed in nigeLab.workflow.
%
%  defaultHotkeyHelpFcn();  Print help for all hotkeys to command window
%  defaultHotkeyHelpFcn(key_in);  Print help for specific keypress
%
%  As configured, "key_in" is only used when the 'control' key modifier is
%  pressed simultaneously.

%% Print reference links to objects associated with video scoring
clc; % If too much in Command Window, it messes with fprintf it seems
str_b = nigeLab.utils.getNigeLink('nigeLab.libs.behaviorInfo');
str_v = nigeLab.utils.getNigeLink('nigeLab.libs.vidInfo');
str_g = nigeLab.utils.getNigeLink('nigeLab.libs.graphicsUpdater');

nigeLab.utils.cprintf('Comments','\n\nSee also:\n');
fprintf(1,'-->\t%s  \t\t:  Keeps track of behavior (event) information.\n',str_b);
fprintf(1,'-->\t%s \t\t\t:  Keeps track of video information.\n',str_v);
fprintf(1,'-->\t%s  \t:  Listens for changes and updates graphics.\n\n',str_g);

%% List all pairs here
% Fields are key names; values are char arrays describing what they do.
pairs = struct( ...
   'comma',    'Set a trial as "non-stereotyped" (Stereotyped == 0)',...
   'period',   'Set a trial as "stereotyped" (Stereotyped == 1)',...
   't',        'Set or reach frame (Reach == current ts)',...
   'r',        'Set "no reach" for trial (Reach == inf)',...
   'g',        'Set grasp frame (Grasp == current ts)', ...
   'f',        'Set "no grasp" for trial (Grasp == inf)',...
   'b',        'Set "both" frame (Support == current ts)', ...
   'v',        'Set "no support" for trial (Support == inf)',...
   'multiply', 'Set "complete" frame (Complete == current ts)', ...
   'divide',   ['Set "incomplete" for trial (Complete == inf) ' ...
               'e.g. he reached and then left paw out for a long time'],...
   'w',        'Set outcome as Successful (Outcome == 1)',...
   'x',        'Set outcome as Unsuccessful (Outcome == 0)',...
   'e',        ['Set Forelimb as "Right" (Forelimb == 1). ' ...
                '(Press alt + e to set ALL trials as "Right")'], ...
   'q',        ['Set Forelimb as "Left" (Forelimb == 0). ' ...
                '(Press alt + q to set ALL trials as "Left")'], ...
   'a',        'Go to previous FRAME', ...
   'leftarrow','Go to previous TRIAL', ...
   'd',        'Go to next FRAME', ...
   'rightarrow','Go to next TRIAL',...
   's',        ['Press alt + s to SAVE Block. ' ...
      'Note: all scoring is saved automatically this just saves BLOCK'],...
   'numpad0',  'Set number of pellets on platform to zero',...
   'numpad1',  'Set number of pellets on platform to 1',...
   'numpad2',  'Set number of pellets on platform to 2',...
   'numpad3',  'Set number of pellets on platform to 3',...
   'numpad4',  'Set number of pellets on platform to 4',...
   'numpad5',  'Set number of pellets on platform to 5',...
   'numpad6',  'Set number of pellets on platform to 6',...
   'numpad7',  'Set number of pellets on platform to 7',...
   'numpad8',  'Set number of pellets on platform to 8',...
   'numpad9',  'Set number of pellets on platform to 9',...
   'subtract', ['Indicate that pellet IS NOT in usual spot ',...
                'in front of rat (PelletPresent == 0)'],...
   'add',      ['Indicate that pellet IS in usual spot ',...
                'in front of rat (PelletPresent == 1)'],...
   'delete',   'Remove the current trial (TrialMask == 0)',...
   'space',    'Play or Pause the video');

%% Check input and print pairs according to key_in
all_pairs = fieldnames(pairs);
if nargin < 1
   key_in = all_pairs;
else
   if ~iscell(key_in)
      error('key_in should be a cell or cell array input');
   end
end

for i = 1:numel(key_in)
   if ismember(key_in{i},all_pairs)
      printKeyDescriptorPair(key_in{i},pairs.(key_in{i}));
   else
      printKeyDescriptorPair(key_in{i});
   end
end


%%
   % Helper function to print key-descriptor pairs
   function printKeyDescriptorPair(key,descriptor)
      % PRINTKEYDESCRIPTORPAIR  Helper to allow iterative printing of key
      %  and descriptor pairs.
      
      if nargin < 2
         descriptor = 'Unused';
      end
      
      nigeLab.utils.cprintf('*Magenta','\t-->\t%s: ',key);
      nigeLab.utils.cprintf('Text',' %s \n',descriptor);
   end


end