classdef FeaturesUI < handle
   %%  FEATURESUI    Class for displaying features of a set of spikes
   %
   %  obj = FeaturesUI()
   %
   %  --------
   %   INPUTS
   %  --------
   %  --------
   %   OUTPUT
   %  --------
   %    obj       :     FeaturesUI object. Displays clusters in some features
   %                    space and other usefull elementsd as cluster quality
   %
   
   %%
   properties (Access = public)
      ChannelSelector
      SpikeImage
      
      Figure
      Features3D
      FeatX
      FeatY
      Features2D
      
      Data
      Parent
      featInd = [1 2];
      
      Submit
      Confirm
      SpikePanel
      SpikePlot
      
      ClusterLabel
      Exclusions
      FeatureCombos
      Channels
      HasFocus
      ReCluster
      VisibleClusters
      TagLabels
      ZoomSlider
      Available = nan;
   end
   
   properties (Access = private)
      
      nfeat;
      
      nztick = 6;
      zmax
      ztickloc
      zticklab
      
      SD_MAX = 3;
      FEAT_VIEW = [30 30];
      MINSPIKES = 30;
      NFEAT_PLOT_POINTS = 2000;
      NCLUS_MAX = 9;
      COLS = {[0,0,0]; ...
         [0.200000000000000,0.200000000000000,0.900000000000000];...
         [0.800000000000000,0.200000000000000,0.200000000000000];...
         [0.900000000000000,0.800000000000000,0.300000000000000];...
         [0.100000000000000,0.700000000000000,0.100000000000000];...
         [1,0,1];[0.930000000000000,0.690000000000000,0.130000000000000];...
         [0.300000000000000,0.950000000000000,0.950000000000000];...
         [0,0.450000000000000,0.750000000000000]};
      
   end
   
   methods (Access = public)
      function obj = FeaturesUI(sortObj,varargin)
         %%
         for iV = 1:2:numel(varargin) % Can specify properties on construct
            if ~ischar(varargin{iV})
               continue
            end
            p = findprop(obj,varargin{iV});
            if isempty(p)
               continue
            end
            obj.(varargin{iV}) = varargin{iV+1};
         end
         
         %% PARSE FIRST INPUT
         
         if isa(sortObj,'nigeLab.Sort')
            obj.Parent = sortObj;
            obj.ChannelSelector = sortObj.UI.ChannelSelector;
            obj.SpikeImage = sortObj.UI.SpikeImage;
            addlistener(obj.SpikeImage,'MainWindowClosed',@(~,~)obj.ExitFeatures);
            addlistener(obj.ChannelSelector,'NewChannel',@(~,~)obj.PlotFeatures);
            addlistener(obj.SpikeImage,'ClassAssigned',@obj.UpdateClasses);
            obj.Data = obj.Parent.spk;
         elseif isa(sortObj,'nigeLab.libs.ChannelUI')
            obj.Parent = [];
            obj.ChannelSelector = sortObj;
            % Needs 'SpikeImage'
            % Needs 'Data' and data struct name,value pair
         else
            obj.Parent = [];
            obj.ChannelSelector = struct('Channel',1);
            % Needs 'SpikeImage'
            % Needs 'Data' and data struct name,value pair
         end
         
         obj.Init(sortObj);
         obj.PlotFeatures;
      end
      
      PlotFeatures(obj)
      ResetFeatureAxes(obj);
      
      
   end
   
   methods (Access = private)
      
      CountExclusions(obj,ch);
      FeatPopCallback(obj,src,~);
      ExitFeatures(obj);
      
      function Init(obj,sortObj)
         
         %% init graphical objects
         
         obj.Figure = figure('Name','Features', ... 'Units','Normalized',...
            'MenuBar','none',...
            'Units','Normalized',...
            'ToolBar','none',...
            'NumberTitle','off',...
            'Position',[0.050,0.075,0.4,0.450],...
            'Color','k');
         
         
%          obj.VisibleClusters = cellfun(@(x) x.Value, sortObj.UI.SpikeImage.VisibleToggle);
         obj.VisibleClusters = true(obj.NCLUS_MAX,1);
         
         featpanel = uipanel(obj.Figure, ...
            'Units', 'Normalized', ...
            'BackgroundColor','k',...
            'ForegroundColor','k', ...
            'FontSize', 16, ...
            'FontName','Arial',...
            'BorderType','none',...
            'Position',[0.01 0.17 0.98 0.82]);
         
         selectpanel = uipanel(obj.Figure, ...
            'Units', 'Normalized', ...
            'BackgroundColor','k',...
            'ForegroundColor','k', ...
            'FontSize', 16, ...
            'FontName','Arial',...
            'BorderType','none',...
            'Position',[0.01 0.01 0.4 0.15]);
         
         obj.zmax = obj.Data.tMax;
         obj.nztick = min(obj.nztick,round(obj.zmax));
         obj.ztickloc = linspace(0,obj.zmax,obj.nztick);
         obj.zticklab = cell(numel(obj.ztickloc),1);
         for iZ = 1:obj.nztick
            obj.zticklab{iZ,1} = sprintf('%3.1fm',...
               obj.ztickloc(iZ));
         end
         
         obj.nfeat = cellfun(@(x) size(x,2),obj.Data.feat);
         
         obj.Features3D = axes(featpanel,'Color','k', ...
            'XColor','w',...
            'YColor','w',...
            'ZColor','w',...
            'Units','Normalized',...
            'FontSmoothing','off',...
            'nextplot','add',...
            'Position',[0.6 0.125 0.4 0.8],...
            'View',[30 30]);
         
         vals=unique(sortObj.UI.feat.combo(:,1));
         str = sortObj.UI.feat.name(unique(sortObj.UI.feat.combo(:,1)));
         obj.FeatX = uicontrol(selectpanel,...
            'Style','popupmenu',...
            'Units','Normalized',...
            'Position',[0.1  0.6  0.8 0.2],...
            'Tag','Dim1',...
            'UserData',vals,...
            'String',str,...
            'Value',find(vals==obj.featInd(1)));
         obj.FeatX.Callback = {@obj.FeatPopCallback};
         
         ind = sortObj.UI.feat.combo(:,1)==1;
         str = sortObj.UI.feat.name(unique(sortObj.UI.feat.combo(ind,2)));
         vals=unique(sortObj.UI.feat.combo(ind,2));
         
         obj.FeatY = uicontrol(selectpanel,...
            'Style','popupmenu',...
            'Units','Normalized',...
            'Position',[0.1  0.2  0.8 0.2],...
            'Tag','Dim2',...
            'UserData',vals,...
            'String',str,...
            'Value',find(vals==obj.featInd(2)));
         obj.FeatY.Callback = {@obj.FeatPopCallback};
         
         obj.Features2D = axes(featpanel,'Color','k', ...
            'FontSmoothing','off',...
            'zlimmode','manual',...
            'zlim',[0 1], ...
            'alimmode','manual',...
            'alim',[0 1], ...
            'climmode','manual',...
            'clim',[0 1], ...
            'XColor','w',...
            'YColor','w',...
            'ZColor','w',...
            'Units','Normalized',...
            'nextplot','add',...
            'XLimMode','manual',...
            'XLim',[-obj.SD_MAX obj.SD_MAX],...
            'YLimMode','manual',...
            'YLim',[-obj.SD_MAX obj.SD_MAX],...
            'Position',[0.1 0.125 0.4 0.8]);
         
         obj.Exclusions = annotation(featpanel,'textbox','EdgeColor','none',... % Features label
            'Color','w',...
            'FontWeight','bold',...
            'FontName','Arial',...
            'FontSize',16,...
            'String','Features',...
            'HorizontalAlignment','Center',...
            'VerticalAlignment','bottom',...
            'Units','Normalized',...
            'Position',[0.1,0.9,0.8,0.1]);
         
         
      end
      
      
   end
end