classdef FeaturesUI < handle
%%  TITLE 
%  obj = FeaturesUI()
%
%  --------
%   INPUTS
%  --------
%  --------
%   OUTPUT
%  --------
%    obj       :     FeaturesUI object. Displays clusters in some features
%                    space and other usefull elementsd as cluster quality
%

%%
   properties (Access = public)
      Figure
      Features3D
      FeatX
      FeatY
      Features2D

      Data
      Parent
      featInd
      
      Submit
      Confirm
      SpikePanel
      SpikePlot
      SpikeImage
      ClusterLabel
      Exclusions
      FeatureCombos
      Channels
      HasFocus
      ReCluster
      VisibleClusters
      TagLabels
      ZoomSlider
      Available = nan;
   end
   
   properties (Access = private)
      NumClus_Max;  
   end
   
   methods (Access = public)
      function obj = FeaturesUI(sortObj,varargin)
          %% 
          for iV = 1:2:numel(varargin) % Can specify properties on construct
            if ~ischar(varargin{iV})
               continue
            end
            p = findprop(obj,varargin{iV});
            if isempty(p)
               continue
            end
            obj.(varargin{iV}) = varargin{iV+1};
         end
         
         %% PARSE FIRST INPUT
         if isa(sortObj,'nigeLab.Sort')
            obj.Parent = sortObj;
            fs = obj.Parent.spk.fs;
            obj.Data = obj.Parent.spk;
            obj.NumClus_Max = sortObj.UI.SpikeImage.NumClus_Max;
            obj.featInd=[1 2];
%             class = obj.Parent.spk.class;
%             spikes = obj.Parent.spk.spikes;
         else
            obj.Parent = struct(...
               'spk',struct('fs',fs,'class',[],'spikes',[]),...
               'UI',struct('ch',1));
            obj.Parent.spk.class = {class};
            obj.Parent.spk.spikes = {spikes};
         end
         obj.Init(sortObj);
         obj.PlotFeatures;
      end
      
      PlotFeatures(obj)
      
   end
   
   methods (Access = private)
        
       FeatPopCallback(obj,src,~)
       
      function Init(obj,sortObj)
          
          %% init graphical objects
          
         obj.Figure = figure('Name','Features', ... 'Units','Normalized',...
             'MenuBar','none',...
             'Units','Normalized',...
             'ToolBar','none',...
             'NumberTitle','off',...
             'Position',[0.050,0.075,0.4,0.450],...
             'Color','k');

         % Panel with control buttons and cluster list
%          ctrlpanel = uipanel(obj.Figure, ...
%             'Units','Normalized', ...
%             'BackgroundColor','k', ...
%             'ForegroundColor','w', ...
%             'FontSize',18,...
%             'FontName', 'Arial', ...
%             'BorderType','none',...
%             'Position',[0.825 0.025 0.15 0.925]);
        
         % Panel for selecting which clusters to show in feature panel
%          visionpanel = uipanel(ctrlpanel,...
%             'Units','Normalized',...
%             'BackgroundColor','k',...
%             'ForegroundColor','k',...
%             'BorderType','none',...
%             'Position',[0.025 0.5 0.95 0.475]);
         
         
         
         
         obj.VisibleClusters = cellfun(@(x) x.Value, sortObj.UI.SpikeImage.VisibleToggle);
%          obj.TagLabels = cell(1,sortObj.NCLUS_MAX);
%          obj.ZoomSlider = uicontrol(visionpanel,'Style','slider', ...
%                            'Units','Normalized',...
%                            'BackgroundColor','w',...
%                            'ForegroundColor','k',...
%                            'FontSize',16,...
%                            'FontName','Arial',...
%                            'Max',500,...
%                            'Min',50,...
%                            'Value',100,...
%                            'ToolTipString','Zoom %',...
%                            'Position',[0.925 0.167 0.065 0.66],...
%                            'Callback',{@CRC_ZoomSlide,obj});
                        
                        
%          for iN = 1:sortObj.NCLUS_MAX
%             obj.VisibleFeatures{iN} = annotation(visionpanel,...
%                'textbox',...
%                'Units','Normalized',...
%                'Position',[0.1 1-(iN/(sortObj.NCLUS_MAX+1)+0.05) 0.39 0.075],...
%                'FontName','Arial',...
%                'FontSize',14,...
%                'FontWeight','bold',...
%                'HorizontalAlignment','center',...
%                'VerticalAlignment','middle',...
%                'Color','k',...
%                'EdgeColor','w',...
%                'LineWidth',3,...
%                'BackgroundColor','k',...
%                'UserData',true,...
%                'ButtonDownFcn',{@CRC_ToggleVision,obj});
%             if isempty(sortObj.cl.tag.defs{iN})
%                tags_val = 1;
%             else
%                tags_val = find(ismember(sortObj.Labels(2:end),...
%                   sortObj.cl.tag.defs(iN)),1,'first');
%                if isempty(tags_val)
%                   tags_val = 1;
%                else
%                   tags_val = tags_val + 1;
%                end
%             end
%             obj.TagLabels{iN} = uicontrol(visionpanel,...
%                'Style','popupmenu',...
%                'String',sortObj.Labels,...
%                'FontName','Arial',...
%                'FontSize',14,...
%                'HorizontalAlignment','center',...
%                'ForegroundColor','w',...
%                'BackgroundColor','k',...
%                'UserData',iN,...
%                'Value',tags_val,...
%                'Units','Normalized',...
%                'Position',[0.51 1-(iN/(sortObj.NCLUS_MAX+1)+0.0575) 0.39 0.075],...
%                'Callback',{@CRC_UpdateTag,obj});
%             
%             if iN > 1
%                str = sprintf('Cluster %d',iN-1);
%                obj.VisibleFeatures{iN}.BackgroundColor = sortObj.COLS{iN};
%             else
%                str = 'OUT';
%                obj.VisibleFeatures{iN}.Color = 'w';
%                obj.VisibleFeatures{iN}.UserData = false;
%                obj.VisibleFeatures{iN}.EdgeColor = [0.66 0.66 0.66];
%                obj.VisibleFeatures{iN}.LineWidth = 2;
%                obj.TagLabels{iN}.Value = 11;
%             end
%             obj.VisibleFeatures{iN}.String = str;
%          end
%          
         
         
%          obj.SpikePlot = cell(sortObj.NCLUS_MAX,1);
%          obj.ClusterLabel = cell(sortObj.NCLUS_MAX,1);

%          featurepanel = uipanel(obj.Figure,'Units','Normalized',...
%             'BackgroundColor','k',...
%             'ForegroundColor','k',...
%             'BorderType','none',...
%             'Position',[0.65 0.025 0.15 0.925]);
         
         featpanel = uipanel(obj.Figure, ...
            'Units', 'Normalized', ...
            'BackgroundColor','k',...
            'ForegroundColor','k', ...
            'FontSize', 16, ...
            'FontName','Arial',...
            'BorderType','none',...
            'Position',[0.01 0.17 0.98 0.82]);
        
        slectpanel = uipanel(obj.Figure, ...
            'Units', 'Normalized', ...
            'BackgroundColor','k',...
            'ForegroundColor','k', ...
            'FontSize', 16, ...
            'FontName','Arial',...
            'BorderType','none',...
            'Position',[0.01 0.01 0.4 0.15]);
         
%          sortObj.NZTICK = min(sortObj.NZTICK,round(sortObj.zmax));
%          sortObj.zticklocs = linspace(0,sortObj.zmax,sortObj.NZTICK);
%          sortObj.zticklab = cell(numel(sortObj.zticklocs),1);
%          for iZ = 1:sortObj.NZTICK
%             sortObj.zticklab{iZ,1} = sprintf('%3.1fm',...
%                sortObj.zticklocs(iZ));
%          end
         obj.Features3D = axes(featpanel,'Color','k', ...
            'XColor','w',...
            'YColor','w',...
            'ZColor','w',...
            'Units','Normalized',...
            'FontSmoothing','off',...
            'nextplot','add',...
            'Position',[0.6 0.125 0.4 0.8],...
            'View',[30 30]);
        %             'YTick',[],...
%             'ylimmode','manual',...
%             'ylim',[-sortObj.SDMAX sortObj.SDMAX],...
%             'XTick',[],...
%             'xlimmode','manual',...
%             'xlim',[-sortObj.SDMAX sortObj.SDMAX],...
%             'ZTick',sortObj.zticklocs,...
%             'ZTickLabel',sortObj.zticklab,...
%             'zlimmode','manual',...
%             'zlim',[0 sortObj.zmax],  ...
         
vals=unique(sortObj.UI.feat.combo(:,1));
str = sortObj.UI.feat.name(unique(sortObj.UI.feat.combo(:,1)));
obj.FeatX = uicontrol(slectpanel,...
    'Style','popupmenu',...
    'Units','Normalized',...
    'Position',[0.1  0.6  0.8 0.2],...
    'Tag','Dim1',...
    'UserData',vals,...
    'String',str,...
    'Value',find(vals==obj.featInd(1)));
    obj.FeatX.Callback = {@obj.FeatPopCallback};

ind = sortObj.UI.feat.combo(:,1)==1;
str = sortObj.UI.feat.name(unique(sortObj.UI.feat.combo(ind,2)));
vals=unique(sortObj.UI.feat.combo(ind,2));

obj.FeatY = uicontrol(slectpanel,...
        'Style','popupmenu',...
    'Units','Normalized',...
    'Position',[0.1  0.2  0.8 0.2],...
    'Tag','Dim2',...
    'UserData',vals,...
    'String',str,...
    'Value',find(vals==obj.featInd(2)));
    obj.FeatY.Callback = {@obj.FeatPopCallback};

         obj.Features2D = axes(featpanel,'Color','k', ...
            'FontSmoothing','off',...
            'zlimmode','manual',...
            'zlim',[0 1], ...
            'alimmode','manual',...
            'alim',[0 1], ...
            'climmode','manual',...
            'clim',[0 1], ...
            'XColor','w',...
            'YColor','w',...
            'ZColor','w',...
            'Units','Normalized',...
            'nextplot','add',...
            'Position',[0.1 0.125 0.4 0.8]);
%          'ylimmode','manual',...
%             'ylim',[-sortObj.SDMAX sortObj.SDMAX],...
%             'YTick',[],...
%             'xlimmode','manual',...
%             'xlim',[-sortObj.SDMAX sortObj.SDMAX],...
%             'XTick',[],...
         
%          obj.FeatureCombos = uicontrol(featpanel,'Style','popupmenu',...
%             'Units','Normalized',...
%             'BackgroundColor','w',...
%             'ForegroundColor','k',...
%             'FontSize',14,...
%             'FontName','Arial',...
%             'String',sortObj.featname,...
%             'Callback',{@CRC_FeatPopCallback,obj},...
%             'Position',[0.1 0.01 0.8 0.1]);
         
%          obj.Exclusions = annotation(featpanel,'textbox','EdgeColor','none',... % Features label
%             'Color','w',...
%             'FontWeight','bold',...
%             'FontName','Arial',...
%             'FontSize',16,...
%             'String','Features',...
%             'HorizontalAlignment','Center',...
%             'VerticalAlignment','bottom',...
%             'Units','Normalized',...
%             'Position',[0.1,0.9,0.8,0.1]);
         

      end
      
      
   end
end