function PlotFeatures(obj)
%% PLOTFEATURES  Plot cluster features from SORT UI in 3D and 2D.


% Loop through each subset of 3 features
ch = obj.ChannelSelector.Channel;
aux = obj.Data.feat{ch};
cl = obj.Data.class{ch};

% Get TIME binning vector for plotting features vs time (mins)
ts = obj.Data.ts{ch};

cla(obj.Features3D);
cla(obj.Features2D);

% randomly select spikes to plot
rsel = false(size(obj.Data.spikes{ch},1));

rsel(randi(numel(rsel),1,...
   min(obj.NFEAT_PLOT_POINTS,numel(rsel))))=true;


for iC = 1:obj.NCLUS_MAX
   if obj.nfeat(ch) < max(obj.featInd)
      continue
   end
   
   if obj.VisibleClusters(iC)
      if obj.NFEAT_PLOT_POINTS <= sum(rsel & ...
            cl==iC)
         fi = cl==iC & ...
            rsel;   % include property no more available
      else
         fi = cl==iC;
      end
   else
      fi = [];
   end
   
   X = aux(fi, obj.featInd);
   if sum(fi) > obj.MINSPIKES
      if iC > 1
         scatter3(obj.Features3D, ...
            aux(fi,obj.featInd(1)), ...
            aux(fi,obj.featInd(2)), ...
            ts(fi), ...
            5, 'filled',... % (size; filled markers)
            'MarkerFaceColor',obj.COLS{iC},...
            'MarkerEdgeColor','none', ...
            'Marker','o',...
            'UserData',iC);

         scatter(obj.Features2D,...
            aux(fi,obj.featInd(1)),...
            aux(fi,obj.featInd(2)),...
            5, 'filled',...
            'MarkerFaceColor',obj.COLS{iC},...
            'MarkerEdgeColor','none',...
            'Marker','o',...
            'UserData',iC);
      else
         scatter3(obj.Features3D, ...
            aux(fi,obj.featInd(1)), ...
            aux(fi,obj.featInd(2)), ...
            ts(fi), ...
            5, 'filled',... % (size; filled markers)
            'MarkerFaceColor',[0.15 0.15 0.15],...
            'MarkerEdgeColor','none', ...
            'Marker','o',...
            'UserData',iC);

         scatter(obj.Features2D,...
            aux(fi,obj.featInd(1)),...
            aux(fi,obj.featInd(2)),...
            5, 'filled',...
            'MarkerFaceColor',[0.15 0.15 0.15],...
            'MarkerEdgeColor','none',...
            'Marker','o',...
            'UserData',iC);
      end
   end
   
end

obj.ResetFeatureAxes;

end