function PlotFeatures(obj)
%% CRC_PLOTFEATURES  Plot cluster features in CRC UI in 3D and 2D.
NFEAT = cellfun(@(x) size(x,2),obj.Data.feat);
NCLUS_MAX = obj.NumClus_Max; % for now. Not sure where the number of cluster is defined
NFEAT_PLOT_POINTS = 2000;
MINSPIKES = 30;

% Loop through each subset of 3 features
ch = obj.Parent.UI.ChannelSelector.Channel;
aux = obj.Data.feat{ch};

% Get TIME binning vector for plotting features vs time (mins)
% tmax = numel(obj.Data.peak_train{ch})/obj.Data.fs/60;
tmax = obj.Data.ts{1}(end);
ts = obj.Data.ts{1};

cla(obj.Features3D);
cla(obj.Features2D);

% randmomly select spikes to plot
rsel = false(size(obj.Data.spikes{ch},1));

rsel(randi(numel(rsel),1,...
   min(NFEAT_PLOT_POINTS,numel(rsel))))=true;


for iC = 1:NCLUS_MAX
   if NFEAT(ch) < max(obj.featInd)
      continue
   end
   
   if obj.VisibleClusters(iC)
      if NFEAT_PLOT_POINTS <= sum(rsel & ...
            obj.Data.class{ch}==iC)
         fi = obj.Data.class{ch}==iC & ...
            rsel;   % include property no more available
      else
         fi = obj.Data.class{ch}==iC;
      end
   else
      fi = [];
   end
   
   X = aux(fi, obj.featInd);
   if sum(fi) > MINSPIKES
      if iC > 1
         scatter3(obj.Features3D, ...
            aux(fi,obj.featInd(1)), ...
            aux(fi,obj.featInd(2)), ...
            ts(fi), ...
            5, 'filled',... % (size; filled markers)
            'MarkerFaceColor',obj.Data.COLS{iC},...
            'MarkerEdgeColor','none', ...
            'Marker','o',...
            'UserData',iC);

         scatter(obj.Features2D,...
            aux(fi,obj.featInd(1)),...
            aux(fi,obj.featInd(2)),...
            5, 'filled',...
            'MarkerFaceColor',obj.Data.COLS{iC},...
            'MarkerEdgeColor','none',...
            'Marker','o',...
            'UserData',iC);
      else
         scatter3(obj.Features3D, ...
            aux(fi,obj.featInd(1)), ...
            aux(fi,obj.featInd(2)), ...
            ts(fi), ...
            5, 'filled',... % (size; filled markers)
            'MarkerFaceColor',[0.15 0.15 0.15],...
            'MarkerEdgeColor','none', ...
            'Marker','o',...
            'UserData',iC);

         scatter(obj.Features2D,...
            aux(fi,obj.featInd(1)),...
            aux(fi,obj.featInd(2)),...
            5, 'filled',...
            'MarkerFaceColor',[0.15 0.15 0.15],...
            'MarkerEdgeColor','none',...
            'Marker','o',...
            'UserData',iC);
      end
   end
   
   % Add cluster cylinder if "tick" is enabled
%    if (~isinf(obj.Data.cl.num.rad{ch}(iC)) && ...
%          sum(obj.Data.cl.num.class.in{ch}==iC)>...
%          obj.Data.MINSPIKES)
%       [X,Y,Z] = CRC_DrawCylinder(obj,ch,iC,obj.featInd(1),...
%          obj.featInd(2),...
%          obj.Data.NPOINTS/32);
%       
%       if iC > 1
%          fill3(obj.Features3D, ...
%             X,Y,Z,obj.Data.COLS{iC},...
%             'FaceColor',obj.Data.COLS{iC},...
%             'EdgeColor','none',...
%             'FaceAlpha',0.2);
%       else
%          fill3(obj.Features3D, ...
%             X,Y,Z,obj.Data.COLS{iC},...
%             'FaceColor',[0.15 0.15 0.15],...
%             'EdgeColor','none',...
%             'FaceAlpha',0.2);
%       end
      
%       
%       [X,Y] = CRC_DrawCircle(obj,ch,iC,obj.featInd(1),...
%          obj.featInd(2),...
%          obj.Data.NPOINTS/32);
%       
%       fill(obj.Features2D, ...
%          X,Y,obj.Data.COLS{iC},...
%          'FaceColor',obj.Data.COLS{iC},...
%          'EdgeColor','none',...
%          'FaceAlpha',0.2);
%    end
end

% CRC_CountExclusions(obj,ch);
% CRC_ResetFeatureAxes(obj);

end