function ResetFeatureAxes(obj)
%% CRC_RESETFEATUREAXES Reset the feature axes with manual limits for speed

%% 3D
% Reset the manual properties of 3D axis
set(obj.Features3D,...
   'xlimmode','manual',...
   'xlim',[-obj.SD_MAX,obj.SD_MAX],...
   'ylimmode','manual',...
   'ylim',[-obj.SD_MAX,obj.SD_MAX],...
   'zlimmode','manual',...
   'zlim',[0 obj.zmax], ...
   'ztick',obj.ztickloc,...
   'zticklabels',obj.zticklab,...
   'alimmode','manual',...
   'alim',[0 1], ...
   'climmode','manual',...
   'clim',[0 1],...
   'View',obj.FEAT_VIEW);

obj.CountExclusions(obj.ChannelSelector.Channel);


end