function [X,Y,Z] = CRC_DrawCylinder(obj,ch,clust,sel1,sel2,scaling)
%% CRC_DRAWCYLINDER Draws the "time" feature-radius cylinder

X = [cos(0:scaling*pi:2*pi); ...
   cos(0:scaling*pi:2*pi); ...
   cos(scaling*pi:scaling*pi:(2+scaling)*pi); ...
   cos(scaling*pi:scaling*pi:(2+scaling)*pi)]* ...
   obj.Data.cl.num.rad{ch}(clust);
X = X + obj.Data.cl.num.centroid{ch,clust}(sel1);

Y = [sin(0:scaling*pi:2*pi); ...
   sin(0:scaling*pi:2*pi); ...
   sin(scaling*pi:scaling*pi:(2+scaling)*pi); ...
   sin(scaling*pi:scaling*pi:(2+scaling)*pi)] * ...
   obj.Data.cl.num.rad{ch}(clust);
Y = Y + obj.Data.cl.num.centroid{ch,clust}(sel2);

Z = [zeros(1,numel(0:scaling*pi:2*pi)); ...
   ones(1,numel(0:scaling*pi:2*pi)); ...
   ones(1,numel(0:scaling*pi:2*pi)); ...
   zeros(1,numel(0:scaling*pi:2*pi))]*...
   round(obj.Data.zmax);
end