function CRC_ResetFeatureAxes(obj)
%% CRC_RESETFEATUREAXES Reset the feature axes with manual limits for speed

%% 3D
% Reset the manual properties of 3D axis
set(obj.Features3D,...
   'xlimmode','manual',...
   'xlim',[-obj.Data.SDMAX,obj.Data.SDMAX],...
   'ylimmode','manual',...
   'ylim',[-obj.Data.SDMAX,obj.Data.SDMAX],...
   'zlimmode','manual',...
   'zlim',[0 obj.Data.zmax], ...
   'ztick',obj.Data.zticklocs,...
   'zticklabels',obj.Data.zticklab,...
   'alimmode','manual',...
   'alim',[0 1], ...
   'climmode','manual',...
   'clim',[0 1],...
   'View',obj.Data.FEAT_VIEW);


%% 2D
% Figure out what the axes limits should be
ch = obj.Data.UI.ch;
rad = max(min(obj.Data.cl.num.rad{ch}),0.05);
x = get(obj.Features2D.Children,'XData');
y = get(obj.Features2D.Children,'YData');

if ~iscell(x)
   x = {x};
   y = {y};
end

mux = 0; muy = 0;
icount = 0;

for iX = 1:numel(x)
   if (any(isnan(x{iX})) || isempty(x{iX}))
      continue;
   end
   mux = mux + mean(x{iX});
   muy = muy + mean(y{iX});
   icount = icount + 1;
end

% Make sure there are things on the axes, then set the manual limits
if icount < 1
   cla(obj.Features2D)
else
   mux = mux/icount; muy = muy/icount;
   set(obj.Features2D, ...
      'xlimmode','manual',...
      'xlim',[mux - rad*5,mux + rad*5],...
      'ylimmode','manual',...
      'ylim',[muy - rad*2.5,muy + rad*2.5],...
      'zlimmode','manual',...
      'zlim',[0 1],...
      'alimmode','manual',...
      'alim',[0 1], ...
      'climmode','manual',...
      'clim',[0 1]);
end

end