function flag = splitMultiAnimals(animalObj)

 f = figure(...
    'Toolbar','none',...
    'MenuBar','none',...
    'NumberTitle','off',...
    'Units','pixels',...
    'Position',[100 100 600 400],...
     'Color',nigeLab.defaults.nigelColors('bg'));
    tabgroup = uitabgroup(f,'Position',[.05 .05 .9 .9]);
    set(tabgroup,'Units','pixels');tabgroup.Position(2) = 30;set(tabgroup,'Units','normalized')
Tree = [];
TankPath = fileparts(animalObj.Paths.SaveLoc);
for ii =1 : numel(animalObj.Blocks)
    BB = animalObj.Blocks(ii);
    tabpanel = uitab(tabgroup,...
        'Title',BB.Name,...
        'UserData',BB,...
        'BackgroundColor',nigeLab.defaults.nigelColors('sfc'));
    Tree_ = BB.splitMultiAnimals(tabpanel);
   Tree = [Tree Tree_];
   animalObjPaths{ii} = cellfun(@(x) fullfile(TankPath,x),{Tree_.Label},'UniformOutput',false);
end
uAnimals = unique([animalObjPaths{:}]);
for ii= 1:numel(uAnimals)
   an = copy(animalObj);
   an.Paths.SaveLoc = uAnimals{ii};
   [~,Name]=fileparts(uAnimals{ii});
   an.Name = Name;
   an.save;
end

btn1 = uicontrol('Style','pushbutton',...
    'Position',[150 5 50 20],'Callback',{@(h,e,x) ApplyCallback(h,e,x),Tree},...
    'String','Accept','Enable','off','Parent',f,...
    'BackgroundColor',nigeLab.defaults.nigelColors('primary'),...
    'ForegroundColor',nigeLab.defaults.nigelColors('onprimary'),...
    'UserData',false(1,numel(animalObj.Blocks)));

btn2 = uicontrol('Style','pushbutton',...
    'Position',[80 5 50 20],'Callback',{@(h,e,x) copyChangesToAll(h,e,x),Tree},...
    'String','Copy to all','Enable','off','Parent',f,...
    'BackgroundColor',nigeLab.defaults.nigelColors('primary'),...
    'ForegroundColor',nigeLab.defaults.nigelColors('onprimary'));

end %function

function ApplyCallback(h,e,Tree)
if any(~h.UserData)
    answer = questdlg('Copy changes to all?',...
        'Do you want to copy this changes to all blocks?','Yes','No','No');
end
splitMultiAnimals(Tree(1).UserData,Tree);
end

function copyChangesToAll(h,e,x)
   x;
end
